import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar's ROOT is defined here; everything below a root section is still
 * generated from the folder tree.
 *
 * Why not fully autogenerated: the reader's mental model is not the folder
 * layout. API reference and Webhooks live under docs/developers/ because that
 * is where their URLs belong, but somebody looking for endpoints should not
 * have to know they are nested inside "Developers" — so they are promoted to
 * root here. Moving the folders instead would change every published URL.
 *
 * Adding an endpoint page still needs no edit here: the API Doc section is
 * autogenerated from its directory. Order pages with `sidebar_position`.
 *
 * `className` drives the root icons — see "Sidebar root sections" in
 * src/css/custom.css.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'index',
    'getting-started',
    {
      type: 'category',
      label: 'UI Guide',
      className: 'sb-root sb-guide',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/guides',
        description: 'Task-by-task instructions for everyday work.',
      },
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'API Doc',
      className: 'sb-root sb-api',
      collapsed: false,
      link: {type: 'doc', id: 'developers/projects-api/index'},
      items: [{type: 'autogenerated', dirName: 'developers/projects-api'}],
    },
    {
      type: 'category',
      label: 'Developers',
      className: 'sb-root sb-dev',
      collapsed: false,
      link: {type: 'doc', id: 'developers/index'},
      items: ['developers/authentication'],
    },
    {
      type: 'category',
      label: 'Webhooks',
      className: 'sb-root sb-webhook',
      collapsed: true,
      items: ['developers/webhooks', 'developers/troubleshoot-webhooks'],
    },
  ],
};

export default sidebars;
