import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar navigation is generated from the docs/ folder structure:
 * - order pages with `sidebar_position` in frontmatter
 * - configure a folder (label, order, collapsed state) with a _category_.json
 *
 * Nothing to edit here when adding pages — the folder tree IS the config.
 */
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
